name: Test & Deploy to Heroku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [synchronize]

jobs:
  deploy:
    name: Heroku deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "people-api1" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
  
  test:
    name: Execute NodeJS Back end tests
    needs: deploy
    uses: dmircheski/nodeApiTesting/.github/workflows/runTests.yml@master